#cloud-config
package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - docker-compose
  - tailscale
runcmd:
  - systemctl enable --now qemu-guest-agent
  - systemctl enable --now docker
  - systemctl enable --now tailscaled
